# Generated by Django 3.1.3 on 2020-11-21 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Haven',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haven_name', models.TextField(default='', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_link', models.TextField(default='')),
                ('race', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(default='01.01.0000')),
                ('in_favorites', models.IntegerField(default=0)),
                ('found_home', models.BooleanField(default=False)),
                ('take_to_home', models.IntegerField(default=0)),
                ('take_to_walk', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_city', to='api.city')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_gender', to='api.gender')),
                ('haven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets_haven', to='api.haven')),
            ],
        ),
        migrations.CreateModel(
            name='PetsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pets_type', models.CharField(default='', max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(default='', max_length=50)),
                ('operation', models.TextField(default='')),
                ('summ', models.IntegerField(default=0)),
                ('transaction_date', models.DateTimeField(default='2000-01-01 00:00:00')),
                ('transaction_number', models.IntegerField(default=0)),
                ('haven', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='haven_transaction', to='api.haven')),
                ('pet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_transaction', to='api.pets')),
            ],
        ),
        migrations.AddField(
            model_name='pets',
            name='type_of_pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_type', to='api.petstype'),
        ),
    ]
