# Generated by Django 3.1.3 on 2020-11-21 10:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201121_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='pet_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_name_transaction', to='api.pets'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 13, 50, 8, 872593)),
        ),
    ]
