# Generated by Django 3.1.3 on 2020-11-21 10:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201121_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='pet_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='pet_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 13, 53, 55, 363905)),
        ),
    ]
