# Generated by Django 3.1.3 on 2020-11-21 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20201121_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='haven',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 21, 14, 1, 54, 657857)),
        ),
    ]
