# Generated by Django 3.1.3 on 2020-11-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20201121_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.TextField(default='2020-11-21 16:14:48.842281'),
        ),
    ]
