# Generated by Django 3.1.3 on 2020-11-21 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201121_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='summ',
            field=models.FloatField(default=0.0),
        ),
    ]
